# fly.toml file generated for headscale-mic92 on 2022-07-24T15:30:43+02:00

app = "headscale-mic92"

[mounts]
  destination = "/var/lib/headscale"
  source = "headscale"

# HTTPS API
[[services]]
  internal_port = 8080
  [[services.ports]]
    handlers = []
    port = 443

# HTTP for HTTP-01 acme
[[services]]
  internal_port = 8081
  [[services.ports]]
    handlers = []
    port = 80

# GRPC
[[services]]
  internal_port = 50443
  [[services.ports]]
    handlers = []
    port = 50443

# DERP
[[services]]
  internal_port = 3478
  protocol = "udp"
  [[services.ports]]
    handlers = []
    port = 3478

# tailscale
[[services]]
  internal_port = 41641
  protocol = "udp"
  [[services.ports]]
    handlers = []
    port = 41641
