# fly.toml file generated for headscale-mic92 on 2022-07-24T15:30:43+02:00

app = "headscale-mic92"

[mounts]
  destination = "/var/lib/headscale"
  source = "headscale"

#[services]
#
#  [[services.ports]]
#    force_https = true
#    handlers = ["http"]
#    port = 80
