app = "kresd"

[[services]]
  internal_port = "4443"
  protocol = "tcp"

  [[services.ports]]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[[services]]
  internal_port = "8853"
  protocol = "tcp"

  [[services.ports]]
    port = "853"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000

[mounts]
  source="kresdcache"
  destination="/var/cache/knot-resolver"
