---
kind: pipeline
type: exec
name: Build NixOS and home-manager

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  commands:
  - mkdir gcroots
  - nix run --no-write-lock-file --override-input nixpkgs github:Mic92/nixpkgs github:Mic92/drone-nix-scheduler#hydra-eval-jobs -- --workers 4 --gc-roots-dir $PWD/gcroots --flake .# > eval.json
  - nix run --no-write-lock-file --override-input nixpkgs github:Mic92/nixpkgs github:Mic92/drone-nix-scheduler -- eval.json
  environment:
    DRONE_SERVER: https://drone.thalheim.io
    DRONE_TOKEN:
      from_secret: DRONE_TOKEN

- name: upload
  commands:
  - nix path-info --json -r $PWD/gcroots/*.drv > path-info.json
  - nix shell 'nixpkgs#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < path-info.json > paths
  - nix shell 'nixpkgs#cachix' -c cachix push --jobs 32 mic92 < paths
  environment:
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

- name: send irc notification
  commands:
  - "LOGNAME=drone nix run github:Mic92/nur-packages#irc-announce -- irc.r 6667 drone \"#xxx\" \"build $DRONE_SYSTEM_PROTO://$DRONE_SYSTEM_HOST/$DRONE_REPO/$DRONE_BUILD_NUMBER : $DRONE_BUILD_STATUS\" || true"
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: pipeline
type: exec
name: Build nix derivation

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - echo $derivation
  - nix build -L $derivation

trigger:
  event:
  - custom

---
kind: pipeline
type: exec
name: Deploy to eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eve
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.turingmachine
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to eva

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eva
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to rock

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.rock
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@turingmachine
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@eve
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: signature
hmac: 21bd708d139fc8946ed5500bfa264c298a0ae957003e03988a537adb3f472b22

...
