---
kind: pipeline
type: exec
name: Build NixOS and home-manager

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  commands:
  - nix run github:Mic92/drone-nix-scheduler#hydra-eval-jobs --gc-roots-dir $BUILDDIR/gcroots --flake .# > eval.json
  - nix run github:Mic92/drone-nix-scheduler eval.json
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DRONE_SERVER: https://drone.thalheim.io
    DRONE_TOKEN:
      from_secret: DRONE_TOKEN

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: pipeline
type: exec
name: Build nix derivation

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - nix build -L $derivation

trigger:
  event:
  - custom

---
kind: pipeline
type: exec
name: Deploy to eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eve
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.turingmachine
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to eva

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eva
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to rock

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.rock
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@turingmachine
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@eve
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: signature
hmac: 09038c08f1c8f53bb7b0830e8dcd90badab8e15a6262693df762af9645d2de78

...
