---
kind: pipeline
type: docker
name: Build NixOS and home-manager

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: busybox
  commands:
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix shell 'nixpkgs#git' -c nix build -L --out-link $BUILDDIR/gcroots.tmp/result -f ./nixos/ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    NIX_REMOTE: daemon
    PAGER: cat
    PATH: /nix/var/nix/profiles/system/sw/bin/
    USER: root
  volumes:
  - name: nixstore
    path: /nix
  - name: gcroots
    path: /var/lib/drone/nix-build
  - name: nixconf
    path: /etc/nix
  - name: sslcerts
    path: /etc/ssl

- name: upload
  image: busybox
  commands:
  - nix path-info --json -r $BUILDDIR/gcroots/result* > $BUILDDIR/path-info.json
  - nix shell 'nixpkgs#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < $BUILDDIR/path-info.json > paths
  - nix shell 'nixpkgs#cachix' -c cachix push --jobs 32 mic92 < paths
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
    NIX_REMOTE: daemon
    PAGER: cat
    PATH: /nix/var/nix/profiles/system/sw/bin/
    USER: root
  volumes:
  - name: nixstore
    path: /nix
  - name: gcroots
    path: /var/lib/drone/nix-build
  - name: nixconf
    path: /etc/nix
  - name: sslcerts
    path: /etc/ssl
  when:
    event:
      exclude:
      - pull_request
    status:
    - failure
    - success

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

trigger:
  event:
    exclude:
    - promote
    - rollback

---
kind: pipeline
type: docker
name: Deploy NixOS to eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: busybox
  commands:
  - "mkdir -m700 -p $HOME/.ssh && echo \"$DEPLOY_SSH_KEY\" > $HOME/.ssh/id_ed25519 && chmod 400 $HOME/.ssh/id_ed25519\n"
  - cp /nix/var/nix/profiles/system/etc/ssh/ssh_known_hosts $HOME/.ssh/known_hosts
  - nix run .#deploy.eve
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY
    NIX_REMOTE: daemon
    PAGER: cat
    PATH: /nix/var/nix/profiles/system/sw/bin/
    USER: root
  volumes:
  - name: nixstore
    path: /nix
  - name: gcroots
    path: /var/lib/drone/nix-build
  - name: nixconf
    path: /etc/nix
  - name: sslcerts
    path: /etc/ssl

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: docker
name: Deploy NixOS to turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: busybox
  commands:
  - "mkdir -m700 -p $HOME/.ssh && echo \"$DEPLOY_SSH_KEY\" > $HOME/.ssh/id_ed25519 && chmod 400 $HOME/.ssh/id_ed25519\n"
  - cp /nix/var/nix/profiles/system/etc/ssh/ssh_known_hosts $HOME/.ssh/known_hosts
  - nix run .#deploy.turingmachine
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY
    NIX_REMOTE: daemon
    PAGER: cat
    PATH: /nix/var/nix/profiles/system/sw/bin/
    USER: root
  volumes:
  - name: nixstore
    path: /nix
  - name: gcroots
    path: /var/lib/drone/nix-build
  - name: nixconf
    path: /etc/nix
  - name: sslcerts
    path: /etc/ssl

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: docker
name: Deploy NixOS to eva

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  image: busybox
  commands:
  - "mkdir -m700 -p $HOME/.ssh && echo \"$DEPLOY_SSH_KEY\" > $HOME/.ssh/id_ed25519 && chmod 400 $HOME/.ssh/id_ed25519\n"
  - cp /nix/var/nix/profiles/system/etc/ssh/ssh_known_hosts $HOME/.ssh/known_hosts
  - nix run .#deploy.eva
  environment:
    BUILDDIR: /var/lib/drone/nix-build
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY
    NIX_REMOTE: daemon
    PAGER: cat
    PATH: /nix/var/nix/profiles/system/sw/bin/
    USER: root
  volumes:
  - name: nixstore
    path: /nix
  - name: gcroots
    path: /var/lib/drone/nix-build
  - name: nixconf
    path: /etc/nix
  - name: sslcerts
    path: /etc/ssl

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

trigger:
  event:
  - promote
  - rollback

---
kind: signature
hmac: 5cd2d7c2a2f8460010750d145cdaf90d6317fda6f9e1abf995e7d9e9e923f3e1

...
