---
kind: pipeline
name: Build NixOS & home-manager

steps:
- name: test
  image: busybox
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
    BUILDDIR: /var/lib/drone/nix-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  volumes:
    - name: nixstore
      path: /nix
    - name: sslcerts
      path: /etc/ssl
    - name: gcroots
      path: /var/lib/drone/nix-build
  commands:
  - mkdir /etc/nix
  - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  # TODO fix this NIX_PATH impurities in homemanager
  - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix build -L --out-link $BUILDDIR/gcroots.tmp/result -f ./nixos/ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  - |
    if [[ -n "$CACHIX_SIGNING_KEY" ]]; then
      nix path-info --json -r $BUILDDIR/gcroots/result* > $BUILDDIR/path-info.json
      nix shell '.#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < $BUILDDIR/path-info.json > paths
      cat paths
      nix shell '.#cachix' -c cachix push mic92 < paths
    fi
volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl
---
kind: signature
hmac: c635a7c58bf73876436014a03c2e8793c983cfbcf3a6a46f0b4816955dae6956

...
