---
kind: pipeline
type: exec
name: Eval jobsets

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  commands:
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - echo <hydra-eval-jobs>
  - nix run --no-write-lock-file --override-input nixpkgs github:Mic92/nixpkgs https://github.com/Mic92/hydra-eval-jobs github:Mic92/drone-nix-scheduler#hydra-eval-jobs -- --workers 4 --gc-roots-dir $PWD/gcroots --flake .#
  - echo </hydra-eval-jobs>
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  environment:
    BUILDDIR: /var/lib/drone/nix-build

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: pipeline
type: exec
name: Build nix derivation

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  commands:
  - nix build -L $derivation
  environment:
    BUILDDIR: /var/lib/drone/nix-build

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: pipeline
type: exec
name: Deploy to eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eve
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.turingmachine
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to eva

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.eva
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to rock

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.rock
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@turingmachine

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@turingmachine
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: pipeline
type: exec
name: Deploy to joerg@eve

platform:
  os: linux
  arch: amd64

steps:
- name: deploy
  commands:
  - eval $(nix shell nixpkgs#openssh -c ssh-agent) && echo "$DEPLOY_SSH_KEY" | nix shell nixpkgs#openssh -c ssh-add - && nix run .#deploy.joerg@eve
  environment:
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY

trigger:
  event:
  - promote
  - rollback

---
kind: signature
hmac: 7d6741f876c1ceddf317dce62db2ed8e8037e29144cc96eef833e21246ffa85f

...
