---
name: Build NixOS & home-manager
kind: pipeline
type: docker

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

steps:
- name: build
  image: busybox
  commands:
  # TODO fix this NIX_PATH impurities in homemanager
  - ls -la /etc/nix
  - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix build -L --out-link $BUILDDIR/gcroots.tmp/result -f ./nixos/ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
    BUILDDIR: /var/lib/drone/nix-build


- name: upload
  image: busybox
  commands:
  - nix path-info --json -r $BUILDDIR/gcroots/result* > $BUILDDIR/path-info.json
  - nix shell '.#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < $BUILDDIR/path-info.json > paths
  - nix shell '.#cachix' -c cachix push --jobs 32 mic92 < paths
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
    BUILDDIR: /var/lib/drone/nix-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  when:
    event:
      exclude:
        - pull_request

- name: deploy
  image: busybox
  commands:
    - mkdir -m700 -p $HOME/.ssh && echo "$DEPLOY_SSH_KEY" > $HOME/.ssh/id_ed25519 && chmod 400 $HOME/.ssh/id_ed25519
    - cp /nix/var/nix/profiles/system/etc/ssh/ssh_known_hosts .ssh/known_hosts
    # TODO: get rid of NIX_PATH here
    - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
    - $(nix-build ./nixos/eve)
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
  when:
    event:
      - promote
    target:
      - production
---
kind: signature
hmac: faf6ef4742688abcc0b50a93b062353c4c47d3d2cb79dbdb8eb1a6f617af06d4

...
