---
name: Build NixOS & home-manager
kind: pipeline
type: docker

volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
- name: nixconf
  host:
    path: /nix/var/nix/profiles/system/etc/nix
- name: sslcerts
  host:
    path: /nix/var/nix/profiles/system/etc/ssl

steps:
- name: build
  image: busybox
  commands:
  # TODO fix this NIX_PATH impurities in home-manager
  - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - |
    if ! nix shell 'nixpkgs#git' -c nix build -L --out-link $BUILDDIR/gcroots.tmp/result -f ./nixos/ci.nix; then
      ci_fail=1
    fi
    if [[ -n "$CACHIX_SIGNING_KEY" ]]; then
      nix path-info --json -r $BUILDDIR/gcroots/result* > $BUILDDIR/path-info.json
      nix shell 'nixpkgs#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' < $BUILDDIR/path-info.json > paths
      nix shell 'nixpkgs#cachix' -c cachix push --jobs 32 mic92 < paths
    fi
    exit ${ci_fail:-0}
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
    BUILDDIR: /var/lib/drone/nix-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  when:
    event:
      exclude:
        - promote

- name: deploy
  image: busybox
  commands:
    - git submodule update --recursive --remote
    - mkdir -m700 -p $HOME/.ssh && echo "$DEPLOY_SSH_KEY" > $HOME/.ssh/id_ed25519 && chmod 400 $HOME/.ssh/id_ed25519
    - cp /nix/var/nix/profiles/system/etc/ssh/ssh_known_hosts $HOME/.ssh/known_hosts
    # TODO: get rid of NIX_PATH here
    - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
    - $(nix-build ./nixos/eve)
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
    - name: nixconf
      path: /etc/nix
    - name: sslcerts
      path: /etc/ssl
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    PAGER: cat
    USER: root
    DEPLOY_SSH_KEY:
      from_secret: DEPLOY_SSH_KEY
  when:
    event:
      - promote
    target:
      - production
---
kind: signature
hmac: 6648c2bd81e7c0bb758a43bdc3d9b0b490de6b714016822b5517a1f360b1a0fd

...
