---
kind: pipeline
name: Build NixOS & home-manager

steps:
- name: test
  image: busybox
  environment:
    NIX_REMOTE: daemon
    PATH: /nix/var/nix/profiles/system/sw/bin/
    SSL_CERT_FILE: /nix/var/nix/profiles/system/etc/ssl/certs/ca-certificates.crt
    GIT_SSL_CAINFO: /nix/var/nix/profiles/system/etc/ssl/certs/ca-certificates.crt
    CURL_CA_BUNDLE: /nix/var/nix/profiles/system/etc/ssl/certs/ca-certificates.crt
    PAGER: cat
    USER: root
    BUILDDIR: /var/lib/drone/nix-build
    CACHIX_SIGNING_KEY:
      from_secret: CACHIX_SIGNING_KEY
  volumes:
    - name: nixstore
      path: /nix
    - name: gcroots
      path: /var/lib/drone/nix-build
  commands:
  - mkdir /etc/nix
  - echo "experimental-features = nix-command flakes" >> /etc/nix/nix.conf
  # TODO fix this NIX_PATH impurities in homemanager
  - export NIX_PATH=$(nix eval --raw --impure --expr '"nixpkgs=$${(builtins.getFlake (toString ./.)).inputs.nixpkgs}"')
  - rm -rf $BUILDDIR/gcroots.tmp && mkdir -p $BUILDDIR/gcroots.tmp
  - nix build -L --out-link $BUILDDIR/gcroots.tmp/result -f ./nixos/ci.nix
  - rm -rf $BUILDDIR/gcroots && mv $BUILDDIR/gcroots.tmp $BUILDDIR/gcroots
  - |
    if [[ -n "$CACHIX_SIGNING_KEY" ]]; then
      nix path-info --json -r $BUILDDIR/gcroots/result* | \
      nix shell '.#jq' -c jq -r 'map(select(.ca == null and .signatures == null)) | map(.path) | .[]' | \
      nix shell '.#cachix' -c cachix push mic92
    fi
volumes:
- name: nixstore
  host:
    path: /nix
- name: gcroots
  host:
    path: /var/lib/drone/nix-build
---
kind: signature
hmac: 6c66b99a9de43bb5c4c1049120ffddad811237b9b42c8d6479147d1202b1243a

...
