stages:
  - build

build-job:
  stage: build
  script:
    - echo $PATH
    - nix-eval-jobs --workers 4 --gc-roots-dir $(pwd)/gcroot --flake '.#hydraJobs' > jobs
    - jq -r '.drvPath' < jobs | xargs nix-build
