pull_request_rules:
  - name: automatic merge on CI success
    conditions:
      - status-success=continuous-integration/drone/pr
      - author=github-actions
    actions:
      merge:
        method: merge
      delete_head_branch: {}