reporting: "off"
update:
    method: never
gui:
  showFileTree: true
git:
  paging:
    colorArg: always
    pager: delta --syntax-theme "Solarized (light)" --paging=never
customCommands:
  - key: '<c-r>'
    command: 'git rebase --interactive "{{.SelectedLocalCommit.Sha}}"'
    context: 'commits'
    subprocess: true
