keys:
  - &joerg F095F28F7B1BA4DD0D93554EE179454B201E23CA
  - &eve C5A6167F97F68FD053571E8B04188BA1509DCDC5
  - &eva 464E02307E15D115D8D666ADE0BD184A633C5C72
  - &turingmachine 50612B0983F7FA2F1985DA0F30371B437689ACFD
  - &matchbox 13d0b443fe935edf44f9b472d8abdace2bcf8e4b
  - &eddie CC48DB9AC67E71DA343B47D594933BDDF739BEB3
  - &rock F139840C191C75322AC3D4516BE2046130150E21
creation_rules:
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
  - path_regex: eve/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eve
  - path_regex: eva/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eva
  - path_regex: turingmachine/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *turingmachine
  - path_regex: matchbox/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *matchbox
  - path_regex: eddie/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eddie
  - path_regex: secrets/ldap\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eve
      - *eva
      - *rock
  - path_regex: secrets/telegraf\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eva
      - *turingmachine
  - path_regex: rock/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *rock
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eddie
      - *eve
      - *turingmachine
      - *eva
      - *matchbox
      - *rock
