keys:
  - &joerg F095F28F7B1BA4DD0D93554EE179454B201E23CA
  - &eve C5A6167F97F68FD053571E8B04188BA1509DCDC5
  - &eva age1v8zjc47jmlqwefyu66s0d4ke98qr4vnuj3cpvs4z9npfdw833dxqwjrhzv
  - &turingmachine 50612B0983F7FA2F1985DA0F30371B437689ACFD
  - &matchbox 13d0b443fe935edf44f9b472d8abdace2bcf8e4b
  - &eddie CC48DB9AC67E71DA343B47D594933BDDF739BEB3
  - &rock F139840C191C75322AC3D4516BE2046130150E21
  - &bernie 6be0cdb876ff7fcb2e0721bcd05c8bd9edd15816
creation_rules:
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
  - path_regex: eve/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eve
  - path_regex: eva/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
        - *joerg
      age:
        - *eva
  - path_regex: turingmachine/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *turingmachine
  - path_regex: matchbox/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *matchbox
  - path_regex: eddie/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *eddie
  - path_regex: secrets/ldap\.yaml$
    key_groups:
    - pgp:
        - *joerg
        - *eve
        - *rock
      age:
        - *eva
  - path_regex: secrets/telegraf\.yaml$
    key_groups:
    - pgp:
        - *joerg
        - *bernie
        - *turingmachine
      age:
        - *eva
  - path_regex: rock/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *joerg
      - *rock
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
        - *joerg
        - *eddie
        - *eve
        - *turingmachine
        - *matchbox
        - *rock
        - *bernie
      age:
        - *eva
