keys:
  - &joergold F095F28F7B1BA4DD0D93554EE179454B201E23CA
  - &joerg age17n64ahe3wesh8l8lj0zylf4nljdmqn28hvqns2g7hgm9mdkhlsvsjuvkxz
  - &blob64 age1lxw7n9xcnwf8wa83q23j479afp859x9j9x2vk2vgqapxq63kya5s4c76ht
  - &eve C5A6167F97F68FD053571E8B04188BA1509DCDC5
  - &eva age1l5auf2gwt44c7nykau8z3vpesju9307zl6flgzs8njzumgnav4hs26w5qx
  - &turingmachine 50612B0983F7FA2F1985DA0F30371B437689ACFD
  - &matchbox F139840C191C75322AC3D4516BE2046130150E21
  - &bernie 6be0cdb876ff7fcb2e0721bcd05c8bd9edd15816
creation_rules:
  - path_regex: secrets/admins/[^/]+\.yaml$
    key_groups:
    - age:
      - *joerg
  - path_regex: modules/etcd-admin.yaml$
    key_groups:
    - age:
      - *joerg
      - *eva
      pgp:
      - *eve
  # https://github.com/carlpett/terraform-provider-sops does not support age keys yet
  - path_regex: eve/modules/gitlab/[^/]+\.enc.json$
    key_groups:
    - pgp:
      - *joergold
      age:
      - *joerg
  - path_regex: eve/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *eve
      age:
      - *joerg
  - path_regex: eva/secrets/[^/]+\.yaml$
    key_groups:
    - age:
        - *joerg
        - *eva
  - path_regex: blob64/secrets/[^/]+\.yaml$
    key_groups:
    - age:
        - *joerg
        - *blob64
  - path_regex: jarvis/secrets/[^/]+\.yaml$
    key_groups:
    - age:
        - *joerg
  - path_regex: turingmachine/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *turingmachine
      age:
      - *joerg
  - path_regex: matchbox/secrets/[^/]+\.yaml$
    key_groups:
    - age:
      - *joerg
      pgp:
      - *matchbox
  - path_regex: bernie/secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
      - *bernie
      age:
      - *joerg
  - path_regex: secrets/ldap\.yaml$
    key_groups:
    - pgp:
        - *eve
      age:
        - *joerg
        - *eva
  - path_regex: secrets/desktop\.yaml$
    key_groups:
    - pgp:
        - *bernie
        - *turingmachine
      age:
        - *joerg
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
    - pgp:
        - *eve
        - *turingmachine
        - *bernie
        - *matchbox
      age:
        - *eva
        - *joerg
        - *blob64
