prSections:
- title: Nixpkgs
  filters: is:open -is:draft -author:@me repo:NixOS/nixpkgs
- title: Nixpkgs (pings)
  filters: is:open -is:draft involves:@me -author:@me repo:NixOS/nixpkgs
#- title: My Pull Requests
#  filters: is:open author:@me
#- title: Needs My Review
#  filters: is:open review-requested:@me
#- title: Involved
#  filters: is:open involves:@me -author:@me
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 50
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 15
      author:
        width: 15
      lines:
        width: 16
    issues:
      updatedAt:
        width: 7
      repo:
        width: 15
      creator:
        width: 10
      assignees:
        width: 20
  refetchIntervalMinutes: 30
keybindings:
  prs:
    - key: n
      command: >
        tmux new-window -c {{.RepoPath}} 'gh pr diff --patch {{.PrNumber}} | delta | less -R && gh pr view --comments {{.PrNumber}} && nixpkgs-review pr {{.PrNumber}} || cat'
repoPaths:
  NixOS/nixpkgs: ~/git/nixpkgs
pager:
  diff: ""
