name: "Update zsh submodules"
on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron:  '51 2 * * *'
jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Update zsh submodules
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          pr-labels: |                  # Labels to be set on the PR
            merge-queue
